[package]
name = "sal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# 动态库?
# crate-type = ["dylib", "rlib"]

[dependencies]
